# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_tries',
            field=models.IntegerField(),
        ),
    ]
